version: "3"
services:
    php:
        build:
            context: ./src
        ports:
            - "8080:8080"
        environment:
            - ADDRESS=${ADDRESS}
        volumes:
            - ./src:/app
