version: "3"
services:
    php:
        build:
            context: ./src
        ports:
            - "8080:80"
        environment:
            - ADDRESS=${ADDRESS}
        volumes:
            - ./src:/usr/share/nginx/html
